export const pricingPlans = [
  {
    id: 'regular',
    name: 'Regular',
    monthlyPrice: 18,
    annualMonthlyPrice: 15,
    annualTotal: 180,
    description: 'Essential tools for agents getting started',
    trial: 'Start with a 14-day free trial',
    featured: false,
    ctaVariant: 'secondary',
    features: [
      { text: 'Nationwide parcel search', included: true },
      { text: 'Interactive map and parcel layers', included: true },
      { text: 'Basic listing maps', included: true },
      { text: 'Limited property tours', included: true },
      { text: 'Daily data updates', included: true },
      { text: 'Search by mailing address', included: false },
      { text: 'Unlimited maps and tours', included: false },
      { text: 'Advanced search filters', included: false },
    ],
  },
  {
    id: 'plus',
    name: 'Plus',
    monthlyPrice: 24,
    annualMonthlyPrice: 20,
    annualTotal: 240,
    description: 'Unlimited maps and tours for active listings',
    trial: 'Start with a 14-day free trial',
    featured: true,
    ctaVariant: 'primary',
    features: [
      { text: 'Everything in Regular', included: true },
      { text: 'Unlimited listing maps', included: true },
      { text: 'Unlimited property tours', included: true },
      { text: 'Search by mailing address', included: true },
      { text: 'Advanced search filters', included: true },
      { text: 'Professional map builder', included: true },
      { text: 'Priority support', included: true },
      { text: 'Export in multiple formats', included: true },
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    customPrice: true,
    description: 'Brokerages and teams',
    trial: null,
    featured: false,
    ctaVariant: 'secondary',
    contact: true,
    features: [
      { text: 'Everything in Plus', included: true },
      { text: 'Multiple agent accounts', included: true },
      { text: 'Brokerage branding options', included: true },
      { text: 'Custom layer hosting', included: true },
      { text: 'Dedicated support', included: true },
      { text: 'Training and onboarding', included: true },
      { text: 'API access', included: true },
    ],
  },
];

export const pricingHero = {
  badge: 'Simple, Transparent Pricing',
  title: 'Choose Your Plan',
  subtitle: 'Maps and property tours for agents — nationwide parcel data included',
};
